include:
  - local: '.github-mirror-gitlab-ci.yml'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.prepare-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.uv-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.build-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.migration-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.deploy-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.test-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.postpipeline-gitlab-ci.yml'
    ref: 'main'


variables:
  MIGRATION_TYPE: "alembic"

stages:
  - prepare
  - build-and-push
  - test
  - migration
  - deploy
  - down
  - postpipeline