services:
  notification-service:
    build:
      context: .
      args:
        ARTIFACTORY_USER: "__token__"
        ARTIFACTORY_PWD: ${GROUP_TOKEN}
    image: ${DOCKER_IMAGE}
    container_name: notification-service
    ports: # TODO: выделить диапазон портов
      - "49501:9090" # prometheus
      - "49500:46500" # gRPC server
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
#    entrypoint: [ "/bin/bash", "-c", "python app/linkedin_data_provider/service/server/serve.py --env=${SCOPE}" ]
    env_file:
      - .env
networks:
  default:
    external: true
    name: ${CONTAINER_NETWORK}
