"""drop template_id template_data

Revision ID: f03f967b16aa
Revises: a9d53eaee4a2
Create Date: 2026-04-27 13:31:10.343773

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f03f967b16aa"
down_revision: Union[str, Sequence[str], None] = "a9d53eaee4a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_NotificationTable_template_id"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_column("NotificationTable", "template_id", schema="notification")
    op.drop_column("NotificationTable", "template_data", schema="notification")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "NotificationTable",
        sa.Column(
            "template_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        schema="notification",
    )
    op.add_column(
        "NotificationTable",
        sa.Column("template_id", sa.TEXT(), autoincrement=False, nullable=True),
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_template_id"),
        "NotificationTable",
        ["template_id"],
        unique=False,
        schema="notification",
    )
    # ### end Alembic commands ###
