"""init_notifications

Revision ID: e6ba8a64aab4
Revises:
Create Date: 2026-04-26 00:52:23.448174

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6ba8a64aab4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "NotificationTable",
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_email", sa.TEXT(), nullable=True),
        sa.Column("recipient_phone", sa.TEXT(), nullable=True),
        sa.Column("webhook_url", sa.TEXT(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum(
                "analytics",
                "reset_password",
                "linkedin_disconnected",
                "delivery_failed",
                name="notificationtype",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "platform",
                "webhook",
                "whatsapp",
                name="notificationchannel",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                name="notificationpriority",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "PROCESSING",
                "SENT",
                "DELIVERED",
                "FAILED",
                "CANCELLED",
                name="notificationstatus",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column("subject", sa.TEXT(), nullable=True),
        sa.Column("body", sa.TEXT(), nullable=True),
        sa.Column("template_id", sa.TEXT(), nullable=True),
        sa.Column("template_data", sa.JSON(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.TEXT(), nullable=True),
        sa.Column("last_error", sa.TEXT(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_NotificationTable")),
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_channel"),
        "NotificationTable",
        ["channel"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_external_id"),
        "NotificationTable",
        ["external_id"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_id"),
        "NotificationTable",
        ["id"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_next_retry_at"),
        "NotificationTable",
        ["next_retry_at"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_notification_type"),
        "NotificationTable",
        ["notification_type"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_priority"),
        "NotificationTable",
        ["priority"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_recipient_email"),
        "NotificationTable",
        ["recipient_email"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_recipient_id"),
        "NotificationTable",
        ["recipient_id"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_recipient_phone"),
        "NotificationTable",
        ["recipient_phone"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_scheduled_at"),
        "NotificationTable",
        ["scheduled_at"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_status"),
        "NotificationTable",
        ["status"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_NotificationTable_template_id"),
        "NotificationTable",
        ["template_id"],
        unique=False,
        schema="notification",
    )
    op.create_table(
        "basic_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_basic_table")),
        schema="notification",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("basic_table", schema="notification")
    op.drop_index(
        op.f("ix_notification_NotificationTable_template_id"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_status"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_scheduled_at"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_recipient_phone"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_recipient_id"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_recipient_email"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_priority"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_notification_type"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_next_retry_at"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_id"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_external_id"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_NotificationTable_channel"),
        table_name="NotificationTable",
        schema="notification",
    )
    op.drop_table("NotificationTable", schema="notification")
    sa.Enum(
        "analytics",
        "reset_password",
        "linkedin_disconnected",
        "delivery_failed",
        name="notificationtype",
        schema="notification",
    ).drop(op.get_bind())
    sa.Enum(
        "email",
        "platform",
        "webhook",
        "whatsapp",
        name="notificationchannel",
        schema="notification",
    ).drop(op.get_bind())
    sa.Enum(
        "low", "normal", "high", name="notificationpriority", schema="notification"
    ).drop(op.get_bind())
    sa.Enum(
        "PENDING",
        "QUEUED",
        "PROCESSING",
        "SENT",
        "DELIVERED",
        "FAILED",
        "CANCELLED",
        name="notificationstatus",
        schema="notification",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
