"""edit enums

Revision ID: 6faa66019d15
Revises: c1d3e2f4a5b6
Create Date: 2026-04-27 02:45:27.589747

"""

from typing import Sequence
from typing import Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "6faa66019d15"
down_revision: Union[str, Sequence[str], None] = "c1d3e2f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="notification",
        enum_name="notificationtype",
        new_values=[
            "analytics",
            "reset_password",
            "linkedin_disconnected",
            "delivery_failed",
            "greeting",
        ],
        affected_columns=[
            TableReference(
                table_schema="notification",
                table_name="NotificationTable",
                column_name="notification_type",
            ),
            TableReference(
                table_schema="notification",
                table_name="UserNotificationPreferenceTable",
                column_name="notification_type",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="notification",
        enum_name="notificationtype",
        new_values=[
            "analytics",
            "reset_password",
            "linkedin_disconnected",
            "delivery_failed",
        ],
        affected_columns=[
            TableReference(
                table_schema="notification",
                table_name="NotificationTable",
                column_name="notification_type",
            ),
            TableReference(
                table_schema="notification",
                table_name="UserNotificationPreferenceTable",
                column_name="notification_type",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
