"""edit recipients

Revision ID: b376595de8da
Revises: f7402b080ede
Create Date: 2026-04-26 16:25:24.656459

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b376595de8da"
down_revision: Union[str, Sequence[str], None] = "f7402b080ede"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserNotificationPreferenceTable",
        sa.Column("recipient_address", sa.TEXT(), nullable=True),
        schema="notification",
    )
    op.drop_column(
        "UserNotificationPreferenceTable", "recipient_phone", schema="notification"
    )
    op.drop_column(
        "UserNotificationPreferenceTable", "recipient_email", schema="notification"
    )
    op.drop_column(
        "UserNotificationPreferenceTable", "webhook_url", schema="notification"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "UserNotificationPreferenceTable",
        sa.Column("webhook_url", sa.TEXT(), autoincrement=False, nullable=True),
        schema="notification",
    )
    op.add_column(
        "UserNotificationPreferenceTable",
        sa.Column("recipient_email", sa.TEXT(), autoincrement=False, nullable=True),
        schema="notification",
    )
    op.add_column(
        "UserNotificationPreferenceTable",
        sa.Column("recipient_phone", sa.TEXT(), autoincrement=False, nullable=True),
        schema="notification",
    )
    op.drop_column(
        "UserNotificationPreferenceTable", "recipient_address", schema="notification"
    )
    # ### end Alembic commands ###
