"""add_user_notification_preference

Revision ID: f7402b080ede
Revises: e6ba8a64aab4
Create Date: 2026-04-26 15:15:50.485107

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7402b080ede"
down_revision: Union[str, Sequence[str], None] = "e6ba8a64aab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserNotificationPreferenceTable",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "ANALYTICS",
                "RESET_PASSWORD",
                "LINKEDIN_DISCONNECTED",
                "DELIVERY_FAILED",
                name="notificationtype",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "EMAIL",
                "PLATFORM",
                "WEBHOOK",
                "WHATSAPP",
                name="notificationchannel",
                schema="notification",
            ),
            nullable=True,
        ),
        sa.Column("recipient_email", sa.TEXT(), nullable=True),
        sa.Column("recipient_phone", sa.TEXT(), nullable=True),
        sa.Column("webhook_url", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_UserNotificationPreferenceTable")),
        sa.UniqueConstraint(
            "user_id",
            "notification_type",
            "channel",
            name=op.f(
                "uq_UserNotificationPreferenceTable_user_id_notification_type_channel"
            ),
        ),
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_UserNotificationPreferenceTable_channel"),
        "UserNotificationPreferenceTable",
        ["channel"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_UserNotificationPreferenceTable_id"),
        "UserNotificationPreferenceTable",
        ["id"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_UserNotificationPreferenceTable_notification_type"),
        "UserNotificationPreferenceTable",
        ["notification_type"],
        unique=False,
        schema="notification",
    )
    op.create_index(
        op.f("ix_notification_UserNotificationPreferenceTable_user_id"),
        "UserNotificationPreferenceTable",
        ["user_id"],
        unique=False,
        schema="notification",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_UserNotificationPreferenceTable_user_id"),
        table_name="UserNotificationPreferenceTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_UserNotificationPreferenceTable_notification_type"),
        table_name="UserNotificationPreferenceTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_UserNotificationPreferenceTable_id"),
        table_name="UserNotificationPreferenceTable",
        schema="notification",
    )
    op.drop_index(
        op.f("ix_notification_UserNotificationPreferenceTable_channel"),
        table_name="UserNotificationPreferenceTable",
        schema="notification",
    )
    op.drop_table("UserNotificationPreferenceTable", schema="notification")
    # ### end Alembic commands ###
